pipelines:
  branches:
    master:
      - step:
           name: Deploy to prod server
           deployment: Production
           script:
             - pipe: atlassian/scp-deploy:1.2.1
               variables:
                  USER: $DEV_SSH_USER
                  SERVER: $DEV_SSH_SERVER
                  REMOTE_PATH: '/tmp/'
                  LOCAL_PATH: './deploy/*'
                  EXTRA_ARGS: ['-r']
             - pipe: atlassian/ssh-run:0.4.0
               variables:
                  SSH_USER: $DEV_SSH_USER
                  SERVER: $DEV_SSH_SERVER
                  MODE: 'command'
                  COMMAND: > 
                    /bin/bash /tmp/deploy.sh > $DEPLOY_LOG_FILE
                  ENV_VARS: >-
                    TG_BOT_ID=$TG_BOT_ID
                    TG_CHAT_ID=$TG_CHAT_ID
                    TG_TEXT_PREFIX=$TG_TEXT_PREFIX
                    PM2_NAME=$PM2_NAME
                    DEPLOY_LOG_FILE=$DEPLOY_LOG_FILE
                    DEPLOY_DIR=$DEPLOY_DIR
                    RUN_DIR=$RUN_DIR
                    DEPLOY_PORT=$DEPLOY_PORT
                    RUN_PORT=$RUN_PORT
                  DEBUG: 'true'
    staging:
     - step:
           name: Deploy to staging server
           deployment: Staging
           script:
             - pipe: atlassian/ssh-run:0.4.0
               variables:
                  SSH_USER: $DEV_SSH_USER
                  SERVER: $DEV_SSH_SERVER
                  MODE: 'command'
                  COMMAND: > 
                    mkdir /tmp/staging-deploy -p
             - pipe: atlassian/scp-deploy:1.2.1
               variables:
                  USER: $DEV_SSH_USER
                  SERVER: $DEV_SSH_SERVER
                  REMOTE_PATH: '/tmp/staging-deploy/'
                  LOCAL_PATH: './deploy/*'
                  EXTRA_ARGS: ['-r', '-v']
             - pipe: atlassian/ssh-run:0.4.0
               variables:
                  SSH_USER: $DEV_SSH_USER
                  SERVER: $DEV_SSH_SERVER
                  MODE: 'command'
                  COMMAND: > 
                    /bin/bash /tmp/deploy.sh > $DEPLOY_LOG_FILE
                  ENV_VARS: >-
                    TG_BOT_ID=$TG_BOT_ID
                    TG_CHAT_ID=$TG_CHAT_ID
                    TG_TEXT_PREFIX=$TG_TEXT_PREFIX
                    PM2_NAME=$PM2_NAME
                    DEPLOY_LOG_FILE=$DEPLOY_LOG_FILE
                    DEPLOY_DIR=$DEPLOY_DIR
                    RUN_DIR=$RUN_DIR
                    DEPLOY_PORT=$DEPLOY_PORT
                    RUN_PORT=$RUN_PORT
                  DEBUG: 'true'
