name: Remote deploy master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Create temp folder
      run: |
        mkdir -p tmp/${{ vars.DEPLOY_TEMP_DIRNAME }} && cp -r deploy/* tmp/${{ vars.DEPLOY_TEMP_DIRNAME }}
    - name: Copy deploy script to server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: tmp
        remote: /tmp
        host: ${{ secrets.PROD_SSH_HOST }}
        port: ${{ secrets.PROD_SSH_PORT }}
        username: ${{ vars.PROD_SSH_USER }}
        privateKey: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
    - name: Executing deploy script on server
      uses: appleboy/ssh-action@v0.1.8
      env:
        PM2_NAME: ${{ vars.PM2_NAME }}
        DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}
        RUN_DIR: ${{ vars.RUN_DIR }}
        DEPLOY_PORT: ${{ vars.DEPLOY_PORT }}
        RUN_PORT: ${{ vars.RUN_PORT }}
        TG_TEXT_PREFIX: ${{ vars.TG_TEXT_PREFIX }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        TG_BOT_ID: ${{ secrets.TG_BOT_ID }}
      with:
        envs: PM2_NAME,DEPLOY_DIR,RUN_DIR,DEPLOY_PORT,RUN_PORT,TG_TEXT_PREFIX,TG_CHAT_ID,TG_BOT_ID
        host: ${{ secrets.PROD_SSH_HOST }}
        port: ${{ secrets.PROD_SSH_PORT }}
        username: ${{ vars.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
        script: \[ -s "/home/user/.nvm/nvm.sh" ] && \. "/home/user/.nvm/nvm.sh" && nvm use 16 && /bin/bash /tmp/${{ vars.DEPLOY_TEMP_DIRNAME }}/deploy.sh > "/tmp/${{ vars.DEPLOY_TEMP_DIRNAME }}/deploy.log"