name: Remote deploy master
on:
  push:
    branches:
      - git-workflow

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Test ssh
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ vars.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
        script: ls -l
    - uses: actions/checkout@v3
    - name: Check vars
      run: |
        echo "${{ vars.PROD_SSH_USER }} @ ${{ secrets.PROD_SSH_HOST }}" | sed 's/./& /g'
        echo "log: $DEPLOY_LOG_FILE, dir: $DEPLOY_DIR, port: $DEPLOY_PORT"
        ls -l
    - name: Copy deploy script to server ${{ secrets.PROD_SSH_HOST }}
      uses: garygrossgarten/github-action-scp@release
      with:
        local: deploy
        remote: /tmp
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ vars.PROD_SSH_USER }}
        privateKey: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
    - name: Executing deploy script on server
      uses: appleboy/ssh-action@v0.1.8
      with:
        envs: PM2_NAME,DEPLOY_DIR,RUN_DIR,DEPLOY_PORT,RUN_PORT,TG_TEXT_PREFIX,TG_CHAT_ID,TG_BOT_ID,DEPLOY_LOG_FILE
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ vars.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
        script: /bin/bash /tmp/deploy.sh > "$DEPLOY_LOG_FILE"